// Copyright 2026 Muhammad Rakibul Islam
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Guest SDK and host/guest ABI for Kelvane WebAssembly modules.
//!
//! A Kelvane module is a `wasm32-wasip1` `cdylib` that the host
//! ([`kelvane-runtime`]) instantiates in a sandbox and drives through a tiny C
//! ABI. This crate factors out the unsafe linear-memory plumbing so a module
//! only supplies a byte-in / byte-out function and invokes [`export_module!`].
//!
//! ## ABI contract (host ⇄ guest)
//!
//! The guest exports three symbols (generated by [`export_module!`]):
//!
//! * `module_alloc(len: i32) -> i32` — allocate `len` bytes of guest memory and
//!   return a pointer. The host calls this to obtain a buffer, then writes the
//!   input bytes into it.
//! * `process(in_ptr: i32, in_len: i32) -> i64` — read the input, produce
//!   output bytes, and return them **length-delimited**: the high 32 bits of the
//!   return value are the output pointer, the low 32 bits are the output length
//!   (`(ptr << 32) | len`). No NUL-termination guessing, no fixed offsets.
//! * `module_dealloc(ptr: i32, len: i32)` — free a buffer from `module_alloc`.
//!
//! Because the host creates a fresh execution store per call and drops it
//! afterward, guest allocations never leak across calls; `module_dealloc` is
//! provided for completeness and host-side hygiene.

// Guest linear-memory interop is inherently unsafe; this crate is compiled into
// WebAssembly modules where that is expected.
#![allow(unsafe_code)]

use std::alloc::{alloc as sys_alloc, dealloc as sys_dealloc, Layout};

/// Allocate `len` bytes in the guest's linear memory and return a pointer, or
/// `0` on failure (non-positive length or layout error).
pub fn alloc_bytes(len: i32) -> i32 {
    if len <= 0 {
        return 0;
    }
    let layout = match Layout::from_size_align(len as usize, 1) {
        Ok(l) => l,
        Err(_) => return 0,
    };
    // SAFETY: layout has non-zero size (len > 0) and valid alignment (1).
    let ptr = unsafe { sys_alloc(layout) };
    ptr as i32
}

/// Free a buffer previously returned by [`alloc_bytes`]. No-op on a null pointer
/// or non-positive length.
pub fn dealloc_bytes(ptr: i32, len: i32) {
    if ptr == 0 || len <= 0 {
        return;
    }
    let layout = match Layout::from_size_align(len as usize, 1) {
        Ok(l) => l,
        Err(_) => return,
    };
    // SAFETY: ptr/len match a prior alloc_bytes allocation and layout.
    unsafe { sys_dealloc(ptr as *mut u8, layout) };
}

/// Pack a `(pointer, length)` pair into one `i64`: high 32 bits = pointer,
/// low 32 bits = length.
#[inline]
pub fn pack(ptr: i32, len: i32) -> i64 {
    ((ptr as u32 as i64) << 32) | (len as u32 as i64)
}

/// Drive a module's byte-in / byte-out function against a host-provided input
/// buffer and return the packed `(out_ptr << 32) | out_len`.
///
/// This is the wasm32 entry point: pointers are guest linear-memory offsets, so
/// the i32↔pointer casts are lossless there. It is exercised end-to-end by the
/// runtime integration tests (which load real WASM). Empty input yields empty
/// output rather than trapping.
pub fn run<F>(in_ptr: i32, in_len: i32, f: F) -> i64
where
    F: FnOnce(&[u8]) -> Vec<u8>,
{
    let output = if in_ptr != 0 && in_len > 0 {
        // SAFETY: the host guarantees [in_ptr, in_ptr+in_len) is a buffer it just
        // allocated via `module_alloc` and wrote the input into.
        let input = unsafe { std::slice::from_raw_parts(in_ptr as *const u8, in_len as usize) };
        f(input)
    } else {
        f(&[])
    };
    let len = output.len() as i32;
    let out_ptr = alloc_bytes(len);
    if out_ptr != 0 {
        // SAFETY: out_ptr points to `len` freshly allocated bytes.
        unsafe {
            std::ptr::copy_nonoverlapping(output.as_ptr(), out_ptr as *mut u8, output.len());
        }
    }
    pack(out_ptr, len)
}

/// Generate the WASM ABI exports for a module from its byte-in / byte-out
/// function.
///
/// Emits `#[unsafe(no_mangle)]` `process`, `module_alloc`, and `module_dealloc`
/// in the calling crate so the symbols are present in the final `cdylib`
/// (defining them here in the library would risk dead-code elimination).
#[macro_export]
macro_rules! export_module {
    ($handler:path) => {
        /// Host entry point: `(in_ptr, in_len) -> (out_ptr << 32 | out_len)`.
        #[unsafe(no_mangle)]
        pub extern "C" fn process(in_ptr: i32, in_len: i32) -> i64 {
            $crate::run(in_ptr, in_len, $handler)
        }

        /// Allocate `len` bytes of guest memory for the host to fill.
        #[unsafe(no_mangle)]
        pub extern "C" fn module_alloc(len: i32) -> i32 {
            $crate::alloc_bytes(len)
        }

        /// Free a buffer previously returned by `module_alloc`.
        #[unsafe(no_mangle)]
        pub extern "C" fn module_dealloc(ptr: i32, len: i32) {
            $crate::dealloc_bytes(ptr, len)
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    // NOTE: `run`/`alloc_bytes` cast i32↔pointer, which is lossless only under
    // wasm32 (32-bit pointers); they can't be round-tripped on a 64-bit host, so
    // they are validated end-to-end by the runtime integration tests against real
    // WASM. Here we test the pointer-free packing.

    #[test]
    fn pack_splits_into_high_ptr_low_len() {
        let packed = pack(0x1234, 0x56);
        assert_eq!((packed >> 32) as u32, 0x1234);
        assert_eq!((packed & 0xFFFF_FFFF) as u32, 0x56);
    }

    #[test]
    fn pack_handles_full_width() {
        let packed = pack(0x7FFF_FFFF, 0x00AB_CDEF);
        assert_eq!((packed >> 32) as u32, 0x7FFF_FFFF);
        assert_eq!((packed & 0xFFFF_FFFF) as u32, 0x00AB_CDEF);
    }
}
